wandb_version: 1

__cached__setup_devices:
  desc: null
  value:
  - cuda
  - 1
_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
adam_epsilon:
  desc: null
  value: 1.0e-08
balanced_sampler:
  desc: null
  value: true
class_weights:
  desc: null
  value: false
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: false
do_train:
  desc: null
  value: false
dynamic_padding:
  desc: null
  value: true
evaluate_during_training:
  desc: null
  value: true
fp16:
  desc: null
  value: true
fp16_opt_level:
  desc: null
  value: O1
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 5.0e-05
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: null
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
max_grad_norm:
  desc: null
  value: 1.0
max_seq_len:
  desc: null
  value: 256
max_steps:
  desc: null
  value: -1
multilabel:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
num_labels:
  desc: null
  value: 173
num_train_epochs:
  desc: null
  value: 5.0
output_dir:
  desc: null
  value: ./models/test
overwrite_output_dir:
  desc: null
  value: true
per_gpu_eval_batch_size:
  desc: null
  value: 16
per_gpu_train_batch_size:
  desc: null
  value: 16
save_steps:
  desc: null
  value: 10000
save_total_limit:
  desc: null
  value: null
seed:
  desc: null
  value: 1029
smart_batching:
  desc: null
  value: true
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
